name: Release

on:
  release:
    types: [created]

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build Binary
      run: |
        cargo build --release

    - uses: actions/upload-artifact@v4
      with:
        name: 'zermio_cli_linux'
        path: target/release/zermio_cli

    - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: false
        files: target/release/zermio_cli

  windows-release:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build Binary
      run: cargo build --release --target x86_64-pc-windows-gnu

    - uses: actions/upload-artifact@v4
      with:
        name: 'release-windows-x86_64'
        path: target/x86_64-pc-windows-gnu/release/zermio_cli.exe

    - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: false
        files: target/x86_64-pc-windows-gnu/release/zermio_cli.exe
